spring:
  application:
    name: LikeMinded

  profiles: production

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

  datasource:
    url: ${DATABASE_URL}

  jackson:
    serialization:
     WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC

  jwtSecret: ${JWT_SECRET}
  jwtExpirationInMs: 18000000

---
spring:
  profiles:
   active: development

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

  datasource:
    url: jdbc:postgresql://localhost:5438/likeminded
    username: likeminded
    password: password

  jackson:
    serialization:
     WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC

  jwtSecret: SuperSecretKey
  jwtExpirationInMs: 604800000

logging:
  level:
    org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl: ERROR